### ISSUE TITLE
can not get tunnel name

### ISSUE THREAD

**Issue by yangyile1990** [ngrok/ngrok-go#155]
cat ngrok.yaml 
```
authtoken: xxx
version: 2
web_addr: localhost:4035
tunnels:
  ngrok_abc:
    proto: http
    addr: 8080
  ngrok_xyz:
    proto: http
    addr: 8081
  ngrok_123:
    proto: http
    addr: 8082
```

then run.
then 
```

def get_ngrok_tunnels(apikey):
    """获得通道信息"""
    client = ngrok.Client(api_key=apikey)
    for t in client.tunnels.list():
        print(t)
        print(t.public_url)
        print(t.labels)
```
or run:
```
func GetNgrokItems(ctx context.Context, apiKey string) ([]*ngrok.Tunnel, error) {
	config := ngrok.NewClientConfig(apiKey)
	client := tunnels.NewClient(config)
	iter := client.List(new(ngrok.Paging))
	var results []*ngrok.Tunnel
	for iter.Next(ctx) {
		results = append(results, iter.Item())
	}
	if err := iter.Err(); err != nil {
		return nil, errors.WithMessage(err, "wrong")
	}
	return results, nil
}
```
can not get the strings: ngrok_abc ngrok_xyz ngrok_123.
