### ISSUE TITLE
basic-auth is always asking for password

### ISSUE THREAD

**Issue by PandaGab** [ngrok/ngrok-go#93]
Hello ngrok ! 

I am using a configuration file to launch the ngrok service. Inside this configuration, I set basic_auth to a single user:password. When I log to the website, it keeps asking for my password all the time. Here is the configuration :

```yaml
authtoken: xxx
version: "2"
tunnels:
    web-application:
        proto: http
        addr: 8080
        basic_auth:
          - "user:pwd"
```

Thank you,
Gabriel
